### PR TITLE
Added data collection section. That rhymes :)

### LINKED ISSUE #9: 3. Data collection
3.	Data collection -> mention sources, Twitter Strava, mention how it is collected <- inside bounding box of amsterdam

### PR DESCRIPTION
**Pull request by wimspaargaren**
Hi guys, 

Please let me know if changes need to be made. I wasn't totally sure about the Strava part since, I'm not really familiar with it.

Fixes #9.

### CODE REVIEW

**Review by rubenstarmans — APPROVED** [review]
Looks good!

**Review by daanschipper — CHANGES_REQUESTED** [review]
Overal fine document.

Couple pointers:
- Twitter; I wouldn't say the first choice to use is because of its wonderful API, incorporate that somewhere after this sentence "Twitter's streaming API will be used"
- Strava; second sentence is the same as the part of Twitter, mix it up. 2x use of since after each other.
- 'Streaming api will be used' and 'has got a rich API', very general sentences, what information are we exactly gathering, why is the api so rich?
- "With these sources a lot of data which is relevant for the application, can be collected." Change a lot to many, why is this relevant?

**Comment by wimspaargaren** [comment]
@daanschipper adjusted requested changes.

**Comment by daanschipper** [comment]
Looks good! Thanks!

**Pull request merged**
